// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd0IvkdPbkBzFiTgFhrCcZ1IUFGZ9f0K8',
    appId: '1:527042635247:web:f6d12b656a42e79f21021a',
    messagingSenderId: '527042635247',
    projectId: 'amorfiinvent',
    authDomain: 'amorfiinvent.firebaseapp.com',
    databaseURL: 'https://amorfiinvent-default-rtdb.firebaseio.com',
    storageBucket: 'amorfiinvent.appspot.com',
    measurementId: 'G-D34MVHE2MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAniw0jrd14KECLP5UoH_RUVrM5LCj6wxw',
    appId: '1:527042635247:android:a53fdff712b3784f21021a',
    messagingSenderId: '527042635247',
    projectId: 'amorfiinvent',
    databaseURL: 'https://amorfiinvent-default-rtdb.firebaseio.com',
    storageBucket: 'amorfiinvent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVu5Dx59Wp4q7HWhanSxWN8824Hidv8Lk',
    appId: '1:527042635247:ios:998749ca7e78512021021a',
    messagingSenderId: '527042635247',
    projectId: 'amorfiinvent',
    databaseURL: 'https://amorfiinvent-default-rtdb.firebaseio.com',
    storageBucket: 'amorfiinvent.appspot.com',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVu5Dx59Wp4q7HWhanSxWN8824Hidv8Lk',
    appId: '1:527042635247:ios:998749ca7e78512021021a',
    messagingSenderId: '527042635247',
    projectId: 'amorfiinvent',
    databaseURL: 'https://amorfiinvent-default-rtdb.firebaseio.com',
    storageBucket: 'amorfiinvent.appspot.com',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd0IvkdPbkBzFiTgFhrCcZ1IUFGZ9f0K8',
    appId: '1:527042635247:web:3a32219361d07a4f21021a',
    messagingSenderId: '527042635247',
    projectId: 'amorfiinvent',
    authDomain: 'amorfiinvent.firebaseapp.com',
    databaseURL: 'https://amorfiinvent-default-rtdb.firebaseio.com',
    storageBucket: 'amorfiinvent.appspot.com',
    measurementId: 'G-JDHR8YFTN7',
  );
}
